# Generated by Django 4.0.3 on 2022-03-26 13:43

import classroom.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='averrage_score',
            field=models.IntegerField(unique=True, validators=[classroom.validators.validate_negative]),
        ),
    ]
